=== Gerodotry/ParserDOMSAXStAX/src/main/resources/papers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!-- Definition of simple types -->
    <xs:simpleType name="YesNoType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="true"/>
            <xs:enumeration value="false"/>
        </xs:restriction>
    </xs:simpleType>

    <!-- Definition of complex types -->
    <xs:complexType name="CharsType">
        <xs:sequence>
            <xs:element name="Color" type="xs:boolean"/>
            <xs:element name="NumberOfPages" type="xs:positiveInteger"/>
            <xs:element name="Glossy" type="xs:boolean"/>
            <xs:element name="HasSubscriptionIndex" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PaperType">
        <xs:sequence>
            <xs:element name="Title" type="xs:string"/>
            <xs:element name="Type" type="xs:string"/>
            <xs:element name="Monthly" type="YesNoType"/>
            <xs:element name="Chars" type="CharsType"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:element name="Papers">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Paper" type="PaperType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== Gerodotry/ParserDOMSAXStAX/src/main/resources/paper.xml
<?xml version="1.0" encoding="UTF-8"?>
<Papers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="papers.xsd">
    <Paper ID="p1">
        <Title>The Daily News</Title>
        <Type>Newspaper</Type>
        <Monthly>false</Monthly>
        <Chars>
            <Color>true</Color>
            <NumberOfPages>20</NumberOfPages>
            <Glossy>false</Glossy>
            <HasSubscriptionIndex>true</HasSubscriptionIndex>
        </Chars>
    </Paper>
    <Paper ID="p2">
        <Title>Fashion Trends</Title>
        <Type>Magazine</Type>
        <Monthly>true</Monthly>
        <Chars>
            <Color>true</Color>
            <NumberOfPages>50</NumberOfPages>
            <Glossy>true</Glossy>
            <HasSubscriptionIndex>true</HasSubscriptionIndex>
        </Chars>
    </Paper>
    <Paper ID="p3">
        <Title>Local Events</Title>
        <Type>Brochure</Type>
        <Monthly>false</Monthly>
        <Chars>
            <Color>true</Color>
            <NumberOfPages>8</NumberOfPages>
            <Glossy>true</Glossy>
            <HasSubscriptionIndex>false</HasSubscriptionIndex>
        </Chars>
    </Paper>
</Papers>
